services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ../schemas/sql/postgresql:/docker-entrypoint-initdb.d

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ../schemas/sql/mysql:/docker-entrypoint-initdb.d

  cassandra:
    image: cassandra:4
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD_SEEDER: yes
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
      CASSANDRA_AUTHENTICATOR: ${CASSANDRA_AUTHENTICATOR}
      CASSANDRA_AUTHORIZER: ${CASSANDRA_AUTHORIZER}
      CASSANDRA_ROLE_MANAGER: ${CASSANDRA_ROLE_MANAGER}

  # loads keyspace and creates tables
  cassandra-loader:
    image: cassandra:4
    container_name: cassandra-loader
    depends_on:
      - cassandra
    volumes:
      - ../schemas/nosql/cql:/cql-init
    environment:
      CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
    entrypoint: [ "/bin/sh", "-c", "sh /cql-init/init_db.sh" ]

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
    volumes:
      - ../schemas/nosql/cypher:/cypher-init